local L = LibStub("AceLocale-3.0"):NewLocale("NeedyGreedy", "enUS", true)

if L then

L["NeedyGreedy"] = true
L["Displays a table of items and the roll choices players have made on them"] = true
L["Display Items"] = true
L["Number of item columns in the display window"] = true
L["Expiry Time"] = true
L["Minutes after item is received before it is removed from display (0 = forever)"] = true
L["Minimum Quality"] = true
L["Minimum quality of item to be displayed"] = true
L["Graphical Display"] = true
L["Display icons for rolls types instead of text"] = true
L["Detach Tooltip"] = true
L["Display the roll information in a standalone window"] = true
L["Item Names"] = true
L["Toggle the display of the item name in the header"] = true
L["%d of %d"] = true
L["%d-%d of %d"] = true
L["Click"] = true
L["to hide/show detached tooltip"] = true
L["Minimap Icon"] = true
L["Toggle the display of the minimap icon"] = true
L["Shift-Click"] = true
L["to attach/detach tooltip"] = true
L["Filter Loot Messages"] = true
L["Enable filtering of loot roll messages"] = true
L["Alt-Click"] = true
L["to clear item list"] = true
L["General"] = true
L["Profile"] = true
L["Show in party"] = true
L["Display the detached window when joining a party and hide the tooltip when leaving a party"] = true
L["You are not in a party"] = true
L["Hide in combat"] = true
L["Only display the detached window when not in combat"] = true
L["Hide Non-Members"] =  true
L["Only display the names of members currently in your party"] = true
L["Valid commands are: config, report, reset"] = true
L["Nothing to report"] = true
L["Popup when rolling"] = true
L["Automatically show the detached tooltip when an item is being rolled on"] = true
L["Reset on Join Party"] = true
L["Clear the item list when joining a new group"] = true
L["Do you wish to reset NeedyGreedy?"] = true
L["All items have been cleared."] = true
L["Reset in Instance"] = true
L["Clear the item list when entering an instance"] = true
L["Open the configuration menu"] = true
L["Hide the detached tooltip"] = true
L["Generate a text summary"] = true
L["Reset the item list"] = true
L["Show the detached tooltip"] = true
L["Scale"] = true
L["Adjust the scale of the detached tooltip"] = true
L["Detached Tooltip"] = true
L["Lock Tooltip"] = true
L["Adjust the position of the detached tooltip"] = true
L["DataBroker Tooltip"] = true
L["Hide In Raid"] = true
L["Suppress the display of the LibDataBroker tooltip when in a raid"] = true
L["Autohide delay"] = true
L["Time to remain visible after the last item has been received (Popup mode only)"] = true
L["Loot Summary"] = true
L["Print loot roll summary message to chat frame"] = true
L["Highlight Self"] = true
L["Color loot you have won differently"] = true

end
